name: Build Latest Page

on:
  push:
    branches:
      - master

env:
    NODE_VERSION: 8.9.4
    GITHUB_PAGES_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

jobs:
  Update-Github-Pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
            
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
           node-version: ${{ env.NODE_VERSION }}
                  
    - name: Npm Build
      run: |
           npm install
           npm run build --if-present
            
    - name: Deploy To Page
      run: |
           bash ./support/deploy.sh
